# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Irwin/University/AY2023-2024/EE2026/xc7a35tcpg236-1_LAB_PROJECTS/ULTIMATE_FINAL_PROJECT/ULTIMATE_FINAL_PROJECT.srcs/sources_1/ip/logicgate_rom/logicgate_rom.xci
# IP: The module: 'logicgate_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Irwin/University/AY2023-2024/EE2026/xc7a35tcpg236-1_LAB_PROJECTS/ULTIMATE_FINAL_PROJECT/ULTIMATE_FINAL_PROJECT.srcs/sources_1/ip/logicgate_rom/logicgate_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logicgate_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Irwin/University/AY2023-2024/EE2026/xc7a35tcpg236-1_LAB_PROJECTS/ULTIMATE_FINAL_PROJECT/ULTIMATE_FINAL_PROJECT.srcs/sources_1/ip/logicgate_rom/logicgate_rom.xci
# IP: The module: 'logicgate_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Irwin/University/AY2023-2024/EE2026/xc7a35tcpg236-1_LAB_PROJECTS/ULTIMATE_FINAL_PROJECT/ULTIMATE_FINAL_PROJECT.srcs/sources_1/ip/logicgate_rom/logicgate_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logicgate_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
